import numpy as np
import xarray as xr
import crocotools_py.postprocess as post
from datetime import datetime
from colorama import Fore, Style


def _set_cf_common_attrs(ds: xr.Dataset, title: str = None, source: str = None) -> xr.Dataset:
    """
    Add minimal CF-friendly metadata without renaming variables or changing structure.
    Safe: attrs-only.
    """
    ds.attrs.setdefault("Conventions", "CF-1.10")
    ds.attrs.setdefault("featureType", "timeSeries")
    if title is not None:
        ds.attrs.setdefault("title", title)
    if source is not None:
        ds.attrs.setdefault("source", source)
    ds.attrs.setdefault("history", "Generated by crocotools_py.validation.get_model_obs_ts")

    if "time" in ds.coords:
        ds["time"].attrs.setdefault("standard_name", "time")
        ds["time"].attrs.setdefault("axis", "T")

    for cname in ["lon", "longitude"]:
        if cname in ds.coords:
            ds[cname].attrs.setdefault("standard_name", "longitude")
            ds[cname].attrs.setdefault("units", "degrees_east")
            ds[cname].attrs.setdefault("axis", "X")

    for cname in ["lat", "latitude"]:
        if cname in ds.coords:
            ds[cname].attrs.setdefault("standard_name", "latitude")
            ds[cname].attrs.setdefault("units", "degrees_north")
            ds[cname].attrs.setdefault("axis", "Y")

    if "depth" in ds.coords:
        ds["depth"].attrs.setdefault("standard_name", "depth")
        ds["depth"].attrs.setdefault("units", "m")
        ds["depth"].attrs.setdefault("positive", "down")

    return ds


def _set_cf_var_attrs(ds: xr.Dataset) -> xr.Dataset:
    """
    Add minimal CF-ish metadata to common variables if present.
    Safe: attrs-only.
    """
    if "temp" in ds.data_vars:
        ds["temp"].attrs.setdefault("standard_name", "sea_water_temperature")
        ds["temp"].attrs.setdefault("units", "degree_Celsius")
        ds["temp"].attrs.setdefault("long_name", "sea water temperature")

    if "type" in ds.data_vars or "type" in ds.coords:
        try:
            ds["type"].attrs.setdefault("long_name", "station instrument type")
        except Exception:
            pass

    return ds


def _to_scalar(x):
    """
    Safely reduce array-like / DataArray / scalar input to one scalar value.
    Returns np.nan if nothing sensible can be extracted.
    """
    try:
        if hasattr(x, "values"):
            x = x.values
        arr = np.asarray(x)

        if arr.size == 0:
            return np.nan

        if arr.ndim == 0:
            val = arr.item()
            try:
                return float(val)
            except Exception:
                return val

        flat = arr.ravel()
        for val in flat:
            try:
                if np.isfinite(val):
                    return float(val)
            except Exception:
                continue

        val = flat[0]
        try:
            return float(val)
        except Exception:
            return val
    except Exception:
        return np.nan


def _extract_obs_depth_m(ds_obs, requested_depth):
    """
    Observation depth in metres.
    Priority:
    1) explicit obs file depth if present
    2) if requested depth is negative, use abs(requested_depth)
    3) if requested depth is non-negative (surface sigma workflow), use 0.0
    """
    if "depth" in ds_obs.coords:
        val = _to_scalar(ds_obs["depth"])
        if np.isfinite(val):
            return abs(float(val))

    if "depth" in ds_obs.data_vars:
        val = _to_scalar(ds_obs["depth"])
        if np.isfinite(val):
            return abs(float(val))

    if isinstance(requested_depth, (int, float)):
        if requested_depth < 0:
            return abs(float(requested_depth))
        return 0.0

    return np.nan


def _extract_model_point_metadata(model_data, requested_depth):
    """
    Extract model point metadata conservatively from post.get_ts output.
    Returns:
        model_lon, model_lat, model_bathymetry_m, model_sampled_depth_m, model_i_index, model_j_index
    """
    def _get_first_present(names):
        for name in names:
            if name in model_data.coords:
                return _to_scalar(model_data.coords[name])
            if name in model_data.data_vars:
                return _to_scalar(model_data[name])
            if name in model_data:
                return _to_scalar(model_data[name])
        return np.nan

    model_lon = _get_first_present(["lon_rho", "lon", "longitude"])
    model_lat = _get_first_present(["lat_rho", "lat", "latitude"])
    model_bathymetry_m = abs(_get_first_present(["h", "bathymetry", "depth_bottom"]))

    model_i_index = _get_first_present(["xi_rho", "xi", "i_index", "i"])
    model_j_index = _get_first_present(["eta_rho", "eta", "j_index", "j"])

    model_sampled_depth_m = _get_first_present(
        ["sampled_depth_m", "z_rho", "z", "depth_rho", "depth_model", "depth"]
    )

    # Conservative fallbacks only if explicit depth is absent
    if not np.isfinite(model_sampled_depth_m):
        if isinstance(requested_depth, (int, float)):
            if requested_depth < 0:
                model_sampled_depth_m = abs(float(requested_depth))
            else:
                # surface sigma workflow
                model_sampled_depth_m = 0.0
        else:
            model_sampled_depth_m = np.nan

    return (
        model_lon,
        model_lat,
        model_bathymetry_m,
        model_sampled_depth_m,
        model_i_index,
        model_j_index,
    )


def _attach_point_metadata(
    ds,
    obs_lon,
    obs_lat,
    obs_depth_m,
    model_lon,
    model_lat,
    model_bathymetry_m,
    model_sampled_depth_m,
    model_i_index=np.nan,
    model_j_index=np.nan,
):
    """
    Attach requested metadata to output Dataset as scalar coords plus attrs.
    """
    ds = ds.assign_coords({
        "obs_lon": obs_lon,
        "obs_lat": obs_lat,
        "obs_depth_m": obs_depth_m,
        "model_lon": model_lon,
        "model_lat": model_lat,
        "model_bathymetry_m": model_bathymetry_m,
        "model_sampled_depth_m": model_sampled_depth_m,
        "model_i_index": model_i_index,
        "model_j_index": model_j_index,
    })

    ds.attrs["obs_lon"] = obs_lon
    ds.attrs["obs_lat"] = obs_lat
    ds.attrs["obs_depth_m"] = obs_depth_m
    ds.attrs["model_lon"] = model_lon
    ds.attrs["model_lat"] = model_lat
    ds.attrs["model_bathymetry_m"] = model_bathymetry_m
    ds.attrs["model_sampled_depth_m"] = model_sampled_depth_m
    ds.attrs["model_i_index"] = model_i_index
    ds.attrs["model_j_index"] = model_j_index

    return ds


def statistics(model_data, data_obs_model_timeaxis):

    # Convert xarray DataArrays to numpy arrays
    model_data = model_data.values
    insitu_data = data_obs_model_timeaxis.values

    print(f"model_data:{model_data}")
    print(f"insitu_data:{insitu_data}")

    if len(model_data) < 2:
        print("Not enough valid data for statistics.")
        return (np.nan,) * 11

    # Find indices where BOTH are not NaN (minimal but important fix)
    non_nan_indices = (~np.isnan(insitu_data)) & (~np.isnan(model_data))
    print(f"non_nan_indices: {non_nan_indices}")
    model_data = model_data[non_nan_indices]
    insitu_data = insitu_data[non_nan_indices]

    if len(model_data) < 2:
        print("Not enough overlapping valid data for statistics.")
        return (np.nan,) * 11

    # Calculate statistics for insitu_data
    insitu_correlation = np.corrcoef(insitu_data.flatten(), model_data.flatten())[0, 1]

    # ---- CENTERED RMSE ----
    insitu_anom = insitu_data - np.mean(insitu_data)
    model_anom  = model_data  - np.mean(model_data)
    insitu_squared_diff = (insitu_anom - model_anom) ** 2
    insitu_rmse = np.sqrt(np.mean(insitu_squared_diff))
    # -----------------------

    insitu_mean_diff = np.mean(insitu_data)
    insitu_min_value = np.min(insitu_data) if len(insitu_data) > 0 else np.nan
    insitu_max_value = np.max(insitu_data) if len(insitu_data) > 0 else np.nan

    # Calculate statistics for model_data
    model_correlation = np.corrcoef(model_data.flatten(), insitu_data.flatten())[0, 1]

    # ---- CENTERED RMSE (same value; keep your structure) ----
    model_squared_diff = (model_anom - insitu_anom) ** 2
    model_rmse = np.sqrt(np.mean(model_squared_diff))
    # --------------------------------------------------------

    model_mean_diff = np.mean(model_data)
    model_min_value = np.min(model_data) if len(model_data) > 0 else np.nan
    model_max_value = np.max(model_data) if len(model_data) > 0 else np.nan
    model_total_bias = np.mean(np.abs(model_data - insitu_data))

    print(f"insitu_correlation:{insitu_correlation}")
    print(f"insitu_rmse (CENTERED):{insitu_rmse}")
    print(f"insitu_mean_diff,:{insitu_mean_diff}")

    return (insitu_correlation, insitu_rmse, insitu_mean_diff, insitu_min_value, insitu_max_value,
            model_correlation, model_rmse, model_mean_diff, model_min_value, model_max_value, model_total_bias)


def obs_2_model_timeaxis(ds_obs, ds_mod):
    """
    get observations (or other) time onto the model time axis
    """
    model_time = ds_mod["time"]

    # Compute bin edges of the model times
    model_dt = model_time[1] - model_time[0]  # assume constant
    bin_edges = model_time + model_dt / 2
    bin_edges = xr.concat([bin_edges[0] - model_dt, bin_edges], dim="time")

    # Average ds_obs values over each bin
    ds_obs_model_timeaxis = ds_obs.groupby_bins("time", bin_edges, labels=model_time.values).mean(skipna=True)
    ds_obs_model_timeaxis = ds_obs_model_timeaxis.rename({"time_bins": "time"})

    return ds_obs_model_timeaxis


def extract_lat_lon(ds):
    """
    Extract lon/lat from a dataset with multiple fallback name options.
    """
    try:
        long_obs = ds.lon.values
        lat_obs = ds.lat.values

        if long_obs.size > 0 and (long_obs == [0]).any():
            raise ValueError("Undesired output detected in 'longitude': array([0])")
        if lat_obs.size > 0 and (lat_obs == [0]).any():
            raise ValueError("Undesired output detected in 'latitude': array([0])")

    except Exception as ve:
        print(f"Caught an exception: {ve}")
        # fallbacks
        for lo, la in [("lon", "lat"), ("Lon", "Lat"), ("Longitude", "Latitude")]:
            if lo in ds and la in ds:
                return ds[lo].values, ds[la].values
            if lo in ds.coords and la in ds.coords:
                return ds.coords[lo].values, ds.coords[la].values

        # last resort
        try:
            return ds.lon.item(), ds.lat.item()
        except Exception:
            raise

    else:
        print("Longitude and latitude successfully retrieved.")
        return long_obs, lat_obs


def get_model_obs_ts(fname, fname_obs, output_path, var, depth=-1, i_shifted=0, j_shifted=0, Yorig=None):
    """
    Retrieve obs + model time series and package into a NetCDF file on the same time axis.
    """

    ds_obs = xr.open_dataset(fname_obs)

    # --- IMPORTANT: guard obs depth selection ---
    # Your new station NetCDFs have depth as depth(station) (size=1), not depth(time) nor a depth axis.
    # We only select obs depth if obs truly has a multi-depth axis.
    obs_has_depth_axis = ("depth" in ds_obs.dims) and (ds_obs.sizes.get("depth", 0) > 1)

    if obs_has_depth_axis:
        # Only do obs depth selection when user asked for a z-level in metres (negative)
        if np.isscalar(depth) and (depth < 0):
            ds_obs = ds_obs.sel(depth=abs(depth), method="nearest")

    # Make sure time dtype is compatible
    ds_obs["time"] = ds_obs["time"].astype("datetime64[ns]")

    # ---------------- UV GRID DATASETS ----------------
    if (var != "temp") and (var != "salt"):
        long_obs, lat_obs = extract_lat_lon(ds_obs)

        model_data = post.get_ts_uv(
            fname, long_obs, lat_obs, Yorig=Yorig,
            i_shift=0, j_shift=0,
            level=depth,
        )

        da_obs_u = ds_obs.u
        da_obs_v = ds_obs.v

        insitu_u_orig = obs_2_model_timeaxis(da_obs_u, model_data)
        insitu_v_orig = obs_2_model_timeaxis(da_obs_v, model_data)

        model_u_orig = model_data.u.values
        model_v_orig = model_data.v.values

        longitude = ds_obs.lon.values
        latitude = ds_obs.lat.values

        obs_lon = _to_scalar(longitude)
        obs_lat = _to_scalar(latitude)
        obs_depth_m = _extract_obs_depth_m(ds_obs, depth)

        (
            model_lon,
            model_lat,
            model_bathymetry_m,
            model_sampled_depth_m,
            model_i_index,
            model_j_index,
        ) = _extract_model_point_metadata(model_data, depth)

        # --- FIX: scalar-safe depth handling ---
        depth_is_scalar = np.isscalar(depth) or (np.ndim(depth) == 0)

        # We keep your intent: treat single requested depth as 1 depth-level output
        n_depth_levels = 1 if depth_is_scalar else len(depth)

        insitu_correlation_u = np.empty(n_depth_levels)
        insitu_rmse_u = np.empty(n_depth_levels)
        insitu_mean_diff_u = np.empty(n_depth_levels)
        insitu_min_value_u = np.empty(n_depth_levels)
        insitu_max_value_u = np.empty(n_depth_levels)

        model_correlation_u = np.empty(n_depth_levels)
        model_rmse_u = np.empty(n_depth_levels)
        model_mean_diff_u = np.empty(n_depth_levels)
        model_min_value_u = np.empty(n_depth_levels)
        model_max_value_u = np.empty(n_depth_levels)
        model_total_bias_u = np.empty(n_depth_levels)

        insitu_correlation_v = np.empty(n_depth_levels)
        insitu_rmse_v = np.empty(n_depth_levels)
        insitu_mean_diff_v = np.empty(n_depth_levels)
        insitu_min_value_v = np.empty(n_depth_levels)
        insitu_max_value_v = np.empty(n_depth_levels)

        model_correlation_v = np.empty(n_depth_levels)
        model_rmse_v = np.empty(n_depth_levels)
        model_mean_diff_v = np.empty(n_depth_levels)
        model_min_value_v = np.empty(n_depth_levels)
        model_max_value_v = np.empty(n_depth_levels)
        model_total_bias_v = np.empty(n_depth_levels)

        print(f"model_data: {model_data}")

        # ---- Keep your structure: scalar vs list depth ----
        if depth_is_scalar:
            model_data_depth = model_data[var][:]
            obs_data_depth_u = insitu_u_orig[:]
            (insitu_correlation_u, insitu_rmse_u, insitu_mean_diff_u,
             insitu_min_value_u, insitu_max_value_u,
             model_correlation_u, model_rmse_u, model_mean_diff_u,
             model_min_value_u, model_max_value_u, model_total_bias_u) = statistics(model_data_depth, obs_data_depth_u)

            obs_data_depth_v = insitu_v_orig[:]
            (insitu_correlation_v, insitu_rmse_v, insitu_mean_diff_v,
             insitu_min_value_v, insitu_max_value_v,
             model_correlation_v, model_rmse_v, model_mean_diff_v,
             model_min_value_v, model_max_value_v, model_total_bias_v) = statistics(model_data_depth, obs_data_depth_v)

        else:
            for idx_depth, depth_level in enumerate(depth):
                model_data_depth = model_data[var][:, idx_depth]
                obs_data_depth_u = insitu_u_orig[:, idx_depth]
                (insitu_correlation_u[idx_depth], insitu_rmse_u[idx_depth], insitu_mean_diff_u[idx_depth],
                 insitu_min_value_u[idx_depth], insitu_max_value_u[idx_depth],
                 model_correlation_u[idx_depth], model_rmse_u[idx_depth], model_mean_diff_u[idx_depth],
                 model_min_value_u[idx_depth], model_max_value_u[idx_depth], model_total_bias_u[idx_depth]) = statistics(model_data_depth, obs_data_depth_u)

                obs_data_depth_v = insitu_v_orig[:, idx_depth]
                (insitu_correlation_v[idx_depth], insitu_rmse_v[idx_depth], insitu_mean_diff_v[idx_depth],
                 insitu_min_value_v[idx_depth], insitu_max_value_v[idx_depth],
                 model_correlation_v[idx_depth], model_rmse_v[idx_depth], model_mean_diff_v[idx_depth],
                 model_min_value_v[idx_depth], model_max_value_v[idx_depth], model_total_bias_v[idx_depth]) = statistics(model_data_depth, obs_data_depth_v)

        time = model_data.time.values

        if depth_is_scalar:
            depth_coord = abs(depth)
            insitu_da_u = xr.DataArray(insitu_u_orig.values[:, np.newaxis], dims=("time", "depth"),
                                       coords={"time": time, "depth": [depth_coord]})
            model_da_u = xr.DataArray(model_u_orig[:, np.newaxis], dims=("time", "depth"),
                                      coords={"time": time, "depth": [depth_coord]})

            insitu_da_v = xr.DataArray(insitu_v_orig.values[:, np.newaxis], dims=("time", "depth"),
                                       coords={"time": time, "depth": [depth_coord]})
            model_da_v = xr.DataArray(model_v_orig[:, np.newaxis], dims=("time", "depth"),
                                      coords={"time": time, "depth": [depth_coord]})
        else:
            depth_coord = np.abs(np.array(depth))
            insitu_da_u = xr.DataArray(insitu_u_orig.values, dims=("time", "depth"),
                                       coords={"time": time, "depth": depth_coord})
            model_da_u = xr.DataArray(model_u_orig, dims=("time", "depth"),
                                      coords={"time": time, "depth": depth_coord})

            insitu_da_v = xr.DataArray(insitu_v_orig.values, dims=("time", "depth"),
                                       coords={"time": time, "depth": depth_coord})
            model_da_v = xr.DataArray(model_v_orig, dims=("time", "depth"),
                                      coords={"time": time, "depth": depth_coord})

        ds = xr.Dataset({
            "insitu_u": insitu_da_u,
            "insitu_v": insitu_da_v,
            "model_u": model_da_u,
            "model_v": model_da_v
        })

        insitu_seasonal_means = {}
        for season, months in {"JFM":[1,2,3], "AMJ":[4,5,6], "JAS":[7,8,9], "OND":[10,11,12]}.items():
            seasonal_u = insitu_da_u.sel(time=insitu_da_u.time.dt.month.isin(months))
            seasonal_v = insitu_da_v.sel(time=insitu_da_v.time.dt.month.isin(months))
            mag = np.sqrt(seasonal_u**2 + seasonal_v**2)
            insitu_seasonal_means[season] = mag.mean(dim=["time", "depth"]).item()

        model_seasonal_means = {}
        for season, months in {"JFM":[1,2,3], "AMJ":[4,5,6], "JAS":[7,8,9], "OND":[10,11,12]}.items():
            seasonal_u = model_da_u.sel(time=model_da_u.time.dt.month.isin(months))
            seasonal_v = model_da_v.sel(time=model_da_v.time.dt.month.isin(months))
            mag = np.sqrt(seasonal_u**2 + seasonal_v**2)
            model_seasonal_means[season] = mag.mean(dim=["time", "depth"]).item()

        ds.attrs.update({f"insitu_seasonal_mean_{k}": v for k, v in insitu_seasonal_means.items()})
        ds.attrs.update({f"model_seasonal_mean_{k}": v for k, v in model_seasonal_means.items()})

        ds.attrs["longitude"] = longitude
        ds.attrs["latitude"] = latitude
        ds.attrs["h"] = model_data.h.values

        ds = _attach_point_metadata(
            ds,
            obs_lon=obs_lon,
            obs_lat=obs_lat,
            obs_depth_m=obs_depth_m,
            model_lon=model_lon,
            model_lat=model_lat,
            model_bathymetry_m=model_bathymetry_m,
            model_sampled_depth_m=model_sampled_depth_m,
            model_i_index=model_i_index,
            model_j_index=model_j_index,
        )

        ds["insitu_correlation_u"] = insitu_correlation_u
        ds["insitu_rmse_u"] = insitu_rmse_u
        ds["insitu_mean_difference_u"] = insitu_mean_diff_u
        ds["insitu_min_value_u"] = insitu_min_value_u
        ds["insitu_max_value_u"] = insitu_max_value_u

        ds["model_correlation_u"] = model_correlation_u
        ds["model_rmse_u"] = model_rmse_u
        ds["model_mean_difference_u"] = model_mean_diff_u
        ds["model_min_value_u"] = model_min_value_u
        ds["model_max_value_u"] = model_max_value_u
        ds["model_total_bias_u"] = model_total_bias_u

        ds["insitu_correlation_v"] = insitu_correlation_v
        ds["insitu_rmse_v"] = insitu_rmse_v
        ds["insitu_mean_difference_v"] = insitu_mean_diff_v
        ds["insitu_min_value_v"] = insitu_min_value_v
        ds["insitu_max_value_v"] = insitu_max_value_v

        ds["model_correlation_v"] = model_correlation_v
        ds["model_rmse_v"] = model_rmse_v
        ds["model_mean_difference_v"] = model_mean_diff_v
        ds["model_min_value_v"] = model_min_value_v
        ds["model_max_value_v"] = model_max_value_v
        ds["model_total_bias_V"] = model_total_bias_v

        ds = _set_cf_common_attrs(ds)
        ds = _set_cf_var_attrs(ds)

        ds.to_netcdf(output_path)

        print("______________________________________________________________")
        print("NetCDF file saved successfully: This is a u,v grid, full water column dataset i.e. ADCP.")
        print("Output is at: ", Style.BRIGHT + Fore.GREEN + output_path + Style.RESET_ALL)

        return ds

    # ---------------- RHO GRID DATASETS ----------------
    else:
        # lon/lat logic preserved
        if obs_has_depth_axis:
            long_obs = ds_obs.lon.values
            lat_obs = ds_obs.lat.values
        else:
            long_obs, lat_obs = extract_lat_lon(ds_obs)

        # --- smarter Bottom handling ---
        if isinstance(depth, (int, float)) and depth < 0:
            bottom_search = abs(depth)
        else:
            bottom_search = None

        model_data = post.get_ts(
            fname, var, long_obs, lat_obs,
            Yorig=Yorig,
            i_shift=i_shifted,
            j_shift=j_shifted,
            time=slice(None),
            level=depth,
            Bottom=bottom_search
        )

        # --- CRITICAL CHECK: stop if extraction failed ---
        arr = model_data[var].values

        if np.isfinite(arr).sum() == 0:
            raise ValueError(
                f"[FAIL] CROCO extraction returned ALL NaN\n"
                f"lon={long_obs}, lat={lat_obs}, depth={depth}, "
                f"i_shift={i_shifted}, j_shift={j_shifted}"
            )

        h_val = model_data["h"].values
        da_obs = ds_obs[var][:]
        data_obs_model_timeaxis = obs_2_model_timeaxis(da_obs, model_data)

        if obs_has_depth_axis:
            longitude = ds_obs.lon.values
            latitude = ds_obs.lat.values
        else:
            longitude, latitude = extract_lat_lon(ds_obs)

        obs_lon = _to_scalar(longitude)
        obs_lat = _to_scalar(latitude)
        obs_depth_m = _extract_obs_depth_m(ds_obs, depth)

        (
            model_lon,
            model_lat,
            model_bathymetry_m,
            model_sampled_depth_m,
            model_i_index,
            model_j_index,
        ) = _extract_model_point_metadata(model_data, depth)

        # single-depth time series
        if data_obs_model_timeaxis.dims == ("time",):
            model_da_ts = model_data[var][:]

            (insitu_correlation, insitu_rmse, insitu_mean_diff,
             insitu_min_value, insitu_max_value,
             model_correlation, model_rmse, model_mean_diff,
             model_min_value, model_max_value, model_total_bias) = statistics(model_da_ts, data_obs_model_timeaxis)

            time = data_obs_model_timeaxis.time.values
            insitu_da = xr.DataArray(data_obs_model_timeaxis.values, dims=("time"), coords={"time": time})
            model_da = xr.DataArray(model_da_ts.values, dims=("time"), coords={"time": time})

            ds = xr.Dataset({f"insitu_data_{var}": insitu_da, f"model_data_{var}": model_da})

            ds.attrs["longitude"] = longitude
            ds.attrs["latitude"] = latitude

            ds = ds.assign_coords({"longitude": longitude})
            ds = ds.assign_coords({"latitude": latitude})
            ds = ds.assign_coords({"depth": depth})

            ds = _attach_point_metadata(
                ds,
                obs_lon=obs_lon,
                obs_lat=obs_lat,
                obs_depth_m=obs_depth_m,
                model_lon=model_lon,
                model_lat=model_lat,
                model_bathymetry_m=model_bathymetry_m,
                model_sampled_depth_m=model_sampled_depth_m,
                model_i_index=model_i_index,
                model_j_index=model_j_index,
            )

            ds.attrs["insitu_correlation_coefficient"] = insitu_correlation
            ds.attrs["insitu_rmse"] = insitu_rmse
            ds.attrs["insitu_mean_difference"] = insitu_mean_diff
            ds.attrs["insitu_min_value"] = insitu_min_value
            ds.attrs["insitu_max_value"] = insitu_max_value

            ds.attrs["model_correlation_coefficient"] = model_correlation
            ds.attrs["model_rmse"] = model_rmse
            ds.attrs["model_mean_difference"] = model_mean_diff
            ds.attrs["model_min_value"] = model_min_value
            ds.attrs["model_max_value"] = model_max_value
            ds.attrs["model_total_bias"] = model_total_bias
            ds.attrs["h"] = h_val

            # seasonal means
            insitu_seasonal_means = {}
            for season, months in {"JFM":[1,2,3], "AMJ":[4,5,6], "JAS":[7,8,9], "OND":[10,11,12]}.items():
                seasonal = insitu_da.sel(time=insitu_da.time.dt.month.isin(months))
                insitu_seasonal_means[season] = seasonal.mean(dim=["time"]).item()

            model_seasonal_means = {}
            for season, months in {"JFM":[1,2,3], "AMJ":[4,5,6], "JAS":[7,8,9], "OND":[10,11,12]}.items():
                seasonal = model_da.sel(time=model_da.time.dt.month.isin(months))
                model_seasonal_means[season] = seasonal.mean(dim=["time"]).item()

            ds.attrs.update({f"insitu_seasonal_mean_{k}": v for k, v in insitu_seasonal_means.items()})
            ds.attrs.update({f"model_seasonal_mean_{k}": v for k, v in model_seasonal_means.items()})

            ds = _set_cf_common_attrs(ds)
            ds = _set_cf_var_attrs(ds)

            ds.to_netcdf(output_path)

            print("______________________________________________________________")
            print("NetCDF file saved successfully: rho grid, single water depth dataset (ATAP-like).")
            print("Output is at: ", Style.BRIGHT + Fore.GREEN + output_path + Style.RESET_ALL)

            return ds

        # water-column obs (Wirewalker-like)
        else:
            depth_levels = data_obs_model_timeaxis.depth.values
            n_depth_levels = len(depth_levels)

            insitu_correlation = np.empty(n_depth_levels)
            insitu_rmse = np.empty(n_depth_levels)
            insitu_mean_diff = np.empty(n_depth_levels)
            insitu_min_value = np.empty(n_depth_levels)
            insitu_max_value = np.empty(n_depth_levels)

            model_correlation = np.empty(n_depth_levels)
            model_rmse = np.empty(n_depth_levels)
            model_mean_diff = np.empty(n_depth_levels)
            model_min_value = np.empty(n_depth_levels)
            model_max_value = np.empty(n_depth_levels)
            model_total_bias = np.empty(n_depth_levels)

            for idx_depth, depth_level in enumerate(depth_levels):
                model_data_depth = model_data[var][:, idx_depth]
                obs_data_depth = data_obs_model_timeaxis[:, idx_depth]

                (insitu_correlation[idx_depth], insitu_rmse[idx_depth], insitu_mean_diff[idx_depth],
                 insitu_min_value[idx_depth], insitu_max_value[idx_depth],
                 model_correlation[idx_depth], model_rmse[idx_depth], model_mean_diff[idx_depth],
                 model_min_value[idx_depth], model_max_value[idx_depth], model_total_bias[idx_depth]) = statistics(model_data_depth, obs_data_depth)

            insitu_data = data_obs_model_timeaxis.values
            depth_idx = np.arange(insitu_data.shape[1])
            time = data_obs_model_timeaxis.time.values

            eta_rho = data_obs_model_timeaxis.eta_rho.values
            xi_rho = data_obs_model_timeaxis.xi_rho.values
            lon_rho = data_obs_model_timeaxis.lon_rho.values
            lat_rho = data_obs_model_timeaxis.lat_rho.values

            model_da = xr.DataArray(model_data[var].values, dims=("time", "depth"),
                                    coords={"time": time, "depth": depth_idx,
                                            "eta_rho": eta_rho, "xi_rho": xi_rho,
                                            "lon_rho": lon_rho, "lat_rho": lat_rho})

            insitu_da = xr.DataArray(insitu_data, dims=("time", "depth"),
                                     coords={"time": time, "depth": depth_idx,
                                             "eta_rho": eta_rho, "xi_rho": xi_rho,
                                             "lon_rho": lon_rho, "lat_rho": lat_rho})

            ds = xr.Dataset({f"insitu_{var}": insitu_da, f"model_{var}": model_da})

            ds = ds.assign_coords({"longitude": longitude})
            ds = ds.assign_coords({"latitude": latitude})

            ds.attrs["longitude"] = longitude
            ds.attrs["latitude"] = latitude
            ds.attrs["h"] = model_data.h.values

            ds = _attach_point_metadata(
                ds,
                obs_lon=obs_lon,
                obs_lat=obs_lat,
                obs_depth_m=obs_depth_m,
                model_lon=model_lon,
                model_lat=model_lat,
                model_bathymetry_m=model_bathymetry_m,
                model_sampled_depth_m=model_sampled_depth_m,
                model_i_index=model_i_index,
                model_j_index=model_j_index,
            )

            ds["insitu_correlation"] = insitu_correlation
            ds["insitu_rmse"] = insitu_rmse
            ds["insitu_mean_difference"] = insitu_mean_diff
            ds["insitu_min_value"] = insitu_min_value
            ds["insitu_max_value"] = insitu_max_value

            ds["model_correlation"] = model_correlation
            ds["model_rmse"] = model_rmse
            ds["model_mean_difference"] = model_mean_diff
            ds["model_min_value"] = model_min_value
            ds["model_max_value"] = model_max_value
            ds["model_total_bias"] = model_total_bias

            # seasonal means
            insitu_seasonal_means = {}
            for season, months in {"JFM":[1,2,3], "AMJ":[4,5,6], "JAS":[7,8,9], "OND":[10,11,12]}.items():
                seasonal = insitu_da.sel(time=insitu_da.time.dt.month.isin(months))
                insitu_seasonal_means[season] = seasonal.mean(dim=["time"]).values

            model_seasonal_means = {}
            for season, months in {"JFM":[1,2,3], "AMJ":[4,5,6], "JAS":[7,8,9], "OND":[10,11,12]}.items():
                seasonal = model_da.sel(time=model_da.time.dt.month.isin(months))
                model_seasonal_means[season] = seasonal.mean(dim=["time"]).values

            ds.attrs.update({f"insitu_seasonal_mean_{k}": v for k, v in insitu_seasonal_means.items()})
            ds.attrs.update({f"model_seasonal_mean_{k}": v for k, v in model_seasonal_means.items()})

            ds = _set_cf_common_attrs(ds)
            ds = _set_cf_var_attrs(ds)

            ds.to_netcdf(output_path)

            print("______________________________________________________________")
            print("NetCDF file saved successfully (Wirewalker-like).")
            print("Output is at: ", Style.BRIGHT + Fore.GREEN + output_path + Style.RESET_ALL)

            return ds
