# This Dockerfile provides instructions to build a docker container 
# which can be used to run the comman line interface (cli.py)
# for some python functions in this repo.
#
# The docker image is build by .github/workflows/build_cli.yml
#
# This Dockerfile is based on the opendrift Dockerfile - See https://opendrift.github.io
# We bake the somisana_croco environment into the image and use the cli.py as the entry point

FROM condaforge/mambaforge

ENV DEBIAN_FRONTEND noninteractive

RUN mkdir /code
WORKDIR /code

# Install opendrift environment into base conda environment
COPY environment.yml .
RUN mamba env update -n base -f environment.yml

# Install opendrift
ADD . /code
RUN pip install -e .

# Test installation
RUN /bin/bash -c "echo -e \"import crocotools_py.postprocess\" | python"

ENTRYPOINT ["python", "cli.py"]
