name: somisana_croco
channels:
  - conda-forge
dependencies:
  - python=3.10.6
  - matplotlib>=3.5
  - numpy>=1.17
  - scipy>=1.6
  - netcdf4<=1.6.1
  - ffmpeg
  - pyproj>=2.3
  - libgdal>=3.1
  - gdal>=3.1
  - xarray
  - dask
  - cfgrib
  - pygrib
  - xhistogram
  - requests
  - cartopy>=0.20
  - nc-time-axis
  - geojson
  - pynucos>=2.12
  - isodate
  - coloredlogs
  - cmocean
  - utm
  - roaring-landmask>=0.7
  - trajan>=0.1.3
  - spyder=5.3.2
  - zarr
  - pathlib
  - pandas
  - pip
  - pip:
    - motuclient
    - copernicus-marine-client>=0.10.0<0.11.0
