name: somisana_croco
channels:
  - conda-forge
dependencies:
  - python=3.10.6
  - matplotlib>=3.5
  - numpy>=1.17
  - scipy>=1.6
  - pandas
  - netcdf4<=1.6.1
  - ffmpeg
  - xarray>=2023.4.0
  - dask>=2023.4.0
  - cfgrib
  - pygrib
  - cartopy>=0.20
  - cmocean
  # some required packages for croco_pytools
  - wxpython=4.2.0
  - traits=6.4.1
  - traitsui=7.4.2
  - geopandas=0.12.1
  - regionmask=0.9.0
  - pyinterp=2022.10.1
  - gcc>=8.3.0
  - gfortran>=8.3.0
  - netcdf-fortran=4.6.0
  # this is to try and handle dependency issues with compiling with f2py 
  - setuptools=72.1.0
