name: somisana_croco
channels:
  - conda-forge
dependencies:
  - python=3.10.6
  - matplotlib
  - numpy
  - scipy
  - pandas
  - netcdf4
  - ffmpeg
  - xarray
  - dask
  - zarr
  - numcodecs
  - cfgrib
  - pygrib
  - cartopy
  - cmocean
  - utide
  # some required packages for croco_pytools
  - wxpython
  - traits=6.4.1
  - traitsui=7.4.2
  - geopandas
  - regionmask
  - pyinterp
  - gcc
  - gfortran
  - netcdf-fortran
  # this is to try and handle dependency issues with compiling with f2py 
  - setuptools=72.1.0
