name: build and push docker image

on:
  workflow_call:
    inputs:
      # which image are we building? IMAGE_ID can either be `cli`, `matlab`, or `run`
      IMAGE_ID:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  # Set the cli image name using the current branch reference
  envs:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_REF: ${{ steps.BRANCH_REF.outputs.value }}
      IMAGE_NAME: ${{ steps.IMAGE_NAME.outputs.value }}
    steps:
      # Dynamically set the branch ref to the currently executing branch
      - name: Set the BRANCH_REF
        id: BRANCH_REF
        run: |
          echo "value=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Set image name
        id: IMAGE_NAME
        run: |
          echo "value=${{ env.REGISTRY }}/saeon/somisana-croco_${{ inputs.IMAGE_ID }}_${{ steps.BRANCH_REF.outputs.value }}" >> $GITHUB_OUTPUT

  build-and-push-image:
    needs: [envs]
    runs-on: ubuntu-latest
    env:
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      IMAGE_NAME: ${{ needs.envs.outputs.IMAGE_NAME }}
      SHA: sha-${{ github.sha }}
    outputs:
      image: ${{ env.IMAGE_NAME }}:${{ env.SHA }}
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      # 
    steps:
      - name: Check out source code
        uses: actions/checkout@main # change to main
        with:
          ref: ${{ env.BRANCH_REF }}
      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            latest
            ${{ env.SHA }}
      - name: Build and push
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile.${{ inputs.IMAGE_ID }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  pull-image-mims1:
    needs: [envs,build-and-push-image]
    runs-on: mims1
    steps:
      - name: clean up locally existing images and containers
        run: |
          imageid=${{ inputs.IMAGE_ID }}
          # containers
          docker rm $(docker ps -a --filter name=*${imageid}* --quiet=true)
          # images
          docker rmi *${imageid}*
      - name: pull latest docker image to mims server
        run: |
          docker pull ${{ needs.envs.outputs.IMAGE_NAME }}:latest
