name: download regional hycom data

on:
  workflow_call:
    inputs:
      RUN_DATE:
        required: true
        type: string
      RUN_DATE_FORMATTED:
        required: true
        type: string
      BRANCH_REF:
        required: true
        type: string
      HDAYS:
        required: true
        type: string
      FDAYS:
        required: true
        type: string
      RUNNER_NAME:
        required: true
        type: string

env:
  DATA_DIR: /home/somisana/ops/${{ inputs.BRANCH_REF }}/${{ inputs.RUN_DATE }}/downloaded_data

jobs:
  download_hycom:
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - name: Download HYCOM
        run: |
          docker run \
            --user $(id -u):$(id -g) \
            --rm \
            -v ${{ env.DATA_DIR }}/HYCOM:/tmp \
            ghcr.io/saeon/somisana-croco_cli_${{ inputs.BRANCH_REF }}:latest \
            download_hycom \
              --domain 11,36,-39,-25 \
              --run_date ${{ inputs.RUN_DATE_FORMATTED }} \
              --hdays ${{ inputs.HDAYS }} \
              --fdays ${{ inputs.FDAYS }} \
              --savedir '/tmp/'
