name: prepare local directory

on:
  workflow_call:
    inputs:
      RUNNER_NAME:
        description: 'specify the runner name to determine what server we are running on'
        required: true
        type: string
      DOMAIN:
        description: 'directory name used to define the domain e.g. swcape_02' 
        required: true
        type: string
      MODEL:
        description: 'directory name used to define the model e.g.croco_v1.3.1'
        required: true
        type: string
      RUN_DATE:
        description: 'time of T0 of the model run - defined dynamically in run_ops.yml'
        required: true
        type: string
      BRANCH_REF:
        description: 'what branch are we on - defined dynamically in run_ops.yml'
        required: true
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  cleanup-old-rundirs:
    runs-on: ${{ inputs.RUNNER_NAME }}
    continue-on-error: true
    steps:
      - name: Clean /home/somisana/${{ inputs.BRANCH_REF }}/${{ inputs.DOMAIN }}/${{ inputs.MODEL }}
        run: >-
          find \
            /home/somisana/${{ inputs.BRANCH_REF }}/${{ inputs.DOMAIN }}/${{ inputs.MODEL }}/* \
            -maxdepth 0 \
            -type d \
            -ctime +5 \
            -exec \
              rm \
                -rf {} \;
  setup-rundir:
    runs-on: ${{ inputs.RUNNER_NAME }}
    env:
      RUN_DIR: /home/somisana/${{ inputs.BRANCH_REF }}/${{ inputs.DOMAIN }}/${{ inputs.MODEL }}/${{ inputs.RUN_DATE }}
    steps:
      - name: create the directory
        run: |
          rm -rf ${{ env.RUN_DIR }}
          mkdir -p ${{ env.RUN_DIR }}
          chown -R :runners ${{ env.RUN_DIR }}
          chmod -R 774 ${{ env.RUN_DIR }}

      - name: copy configuration files from docker image
        run: >-
          docker run \
            --rm \
            --entrypoint /bin/bash \
            -v ${{ env.RUN_DIR }}:/tmp \
            ghcr.io/saeon/somisana-croco_run_main:latest \
            -c "cp -r /somisana-croco/configs/${{ inputs.DOMAIN }}/${{ inputs.MODEL }}/* /tmp/"

