name: Run SOMISANA forecast models on MIMS

on:
  schedule:
  # the workflow designed to every 6 hours. Optionally it can also be run every 12 or 24 hours
  # initialise once a day at 3am
    - cron: '0 3 * * *'
  # initialise twice a day
  #  - cron: '0 0,12 * * *'
  workflow_dispatch:
    inputs:
      run_date:
        description: 'Date and time for T0 for the run in format YYYYMMDD_HH'
        required: false
        default: ''
        type: string

jobs:
  # note that the jobs aren't executed in the order they are written below
  # they are executed in the order depending on the 'needs' attribute of each job
  build_cli:
    uses: ./.github/workflows/build_images.yml
    with:
      IMAGE_ID: cli

  # set some environment variables
  envs:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_REF: ${{ steps.BRANCH_REF.outputs.value }}
      RUN_DATE: ${{ steps.calculate_date.outputs.value }}
    steps:
      - name: Calculate run_date
        id: calculate_date
        run: |
          input_run_date=${{ github.event.inputs.run_date || 'unspecified' }}
          if [[ ${{ github.event_name }} == 'workflow_dispatch' && ${input_run_date} != 'unspecified' ]]
          then
            run_date="${{ github.event.inputs.run_date }}"  # Use provided run_date
          else
            # automatically set the run_date by finding an appropriate time stamp in the past (corresponding to our cron schedule)
            # Get the current time in UTC
            current_time=$(date -u +'%Y%m%d_%H')
            # Extract the hour and calculate the nearest multiple of 12 in the past (as per our cron schedule above)
            hour=$(echo ${current_time:9:2} | awk '{print int($1 - ($1%12))}')
            # Correct hour formatting (ensure leading zero)
            hour=$(printf "%02d" $hour)
            # Assemble the run_date
            run_date=$(echo ${current_time:0:8}_${hour})
          fi
          echo "value=$run_date" >> $GITHUB_OUTPUT
          
      # Dynamically set the branch ref to the currently executing branch
      - name: Set the BRANCH_REF
        id: BRANCH_REF
        run: |
          echo "value=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
  
  # everything below here runs on self-hosted runners i.e. dedicated servers hosted by DFFE
  # for now we have two, running identical workflows, simply to test the stability of the new server
  # in future, if we had two different servers, we could run different domains/configurations on them in parallel
  # by adding new configurable inputs to run_ops_server.yml 
  #
 
  run_ops_mims1:
    needs: [envs,build_cli]
    uses: ./.github/workflows/run_ops_server.yml 
    with:
      RUNNER_NAME: mims1
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
    secrets: inherit
 
  run_ops_mims3:
    needs: [envs,build_cli]
    uses: ./.github/workflows/run_ops_server.yml 
    with:
      RUNNER_NAME: mims3
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
    secrets: inherit
  
