name: Run SOMISANA forecast models on MIMS

on:
  # commented for now
  #schedule:
    # Runs every 6 hours
    #  - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      run_date:
        description: 'Date and time for the run in format YYYYMMDD HH:MM:SS'
        required: false
        default: ''
        type: string
      build_images:
        description: 'Run the image builds?'
        required: true
        default: 'true'
        type: boolean

jobs:
  build_images:
    if: ${{ github.event.inputs.build_images == 'true' }}  # Conditional execution
    strategy:
      matrix:
        image_id: ['cli', 'run', 'matlab']
    uses: ./.github/workflows/build_images.yml  # Path to your reusable workflow
    with:
      IMAGE_ID: ${{ matrix.image_id }}

  # start by setting some environment variables
  envs:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_REF: ${{ steps.BRANCH_REF.outputs.value }}
      RUN_DATE: ${{ steps.calculate_date.outputs.run_date }}
    steps:
      - name: Calculate run_date
        id: calculate_date
        run: |
          if [[ ${{ github.event_name }} == 'workflow_dispatch' && github.event.inputs.run_date != '' ]]
          then
            run_date="${{ github.event.inputs.run_date }}"  # Use provided run_date
          else
            # Get the current time in UTC
            current_time=$(date -u +'%Y%m%d %H:%M:%S')
            # Calculate the nearest 6-hour interval
            hour=$(echo ${current_time:8:2} | awk '{print $1 - ($1%6)}')
            run_date=$(echo ${current_time:0:8} ${hour}:00:00) 
          fi
          echo "value=$run_date" >> $GITHUB_OUTPUT
          
      # Dynamically set the branch ref to the currently executing branch
      - name: Set the BRANCH_REF
        id: BRANCH_REF
        run: |
          echo "value=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

  check_run_date:
    runs-on: ubuntu-latest
    needs: [envs]
    steps:
      - name: check run date - just for debugging
        run: |
          echo "The run_date is ${{ needs.envs.outputs.RUN_DATE }}"
      
