name: Sandbox for testing individual calleable workflows
# (not used in th operational workflow at all)

on:
  workflow_dispatch:

jobs:
  # note that the jobs aren't executed in the order they are written below
  # they are executed in the order depending on the 'needs' attribute of each job
  build_cli:
    uses: ./.github/workflows/build_images.yml
    with:
      IMAGE_ID: cli
 
  # set some environment variables
  envs:
    runs-on: ubuntu-latest
    outputs:
      BRANCH_REF: ${{ steps.BRANCH_REF.outputs.value }}
      RUN_DATE: ${{ steps.calculate_date.outputs.value }}
    steps:
      - name: Calculate run_date
        id: calculate_date
        run: | 
          input_run_date=${{ github.event.inputs.run_date || 'unspecified' }}
          if [[ ${{ github.event_name }} == 'workflow_dispatch' && ${input_run_date} != 'unspecified' ]]
          then
            run_date="${{ github.event.inputs.run_date }}"  # Use provided run_date
          else
            # automatically set the run_date by finding an appropriate time stamp in the past (corresponding to our cron schedule)
            # Get the current time in UTC
            current_time=$(date -u +'%Y%m%d_%H')
            # Extract the hour and calculate the nearest multiple of 12 in the past (as per our cron schedule above)
            hour=$(echo ${current_time:9:2} | awk '{print int($1 - ($1%12))}')
            # Correct hour formatting (ensure leading zero)
            hour=$(printf "%02d" $hour)
            # Assemble the run_date
            run_date=$(echo ${current_time:0:8}_${hour})
          fi
          echo "value=$run_date" >> $GITHUB_OUTPUT

  download_hycom:
    needs: [envs, build_cli]
    uses: ./.github/workflows/retry_download_hycom.yml
    with:
      RUNNER_NAME: mims1
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      HDAYS: 5
      FDAYS: 5
    secrets: inherit

