name: Sandbox for testing individual calleable workflows
# (not used in th operational workflow at all)

on:
  workflow_dispatch:

jobs:
  build_cli:
    uses: ./.github/workflows/build_images.yml
    with:
      IMAGE_ID: cli

  # Download hycom 
  download_hycom:
    runs-on: mims1
    steps:
      - name: Download HYCOM
        run: |
          docker run \
            --user $(id -u):$(id -g) \
            --rm \
            -v /home/somisana/ops/testing-hycom-download/20250423_00/downloaded_data/HYCOM:/tmp \
            ghcr.io/saeon/somisana-croco_cli_main:latest \
            download_hycom \
            --domain 23,24,-37,-36 \
            --run_date '2025-04-23 00:00:00' \
            --hdays 5 \
            --fdays 5 \
            --savedir '/tmp/' && echo "Download completed" || echo "Download failed"
          shell: bash
