name: Sandbox for testing individual calleable workflows
# (not used in th operational workflow at all)

on:
  workflow_dispatch:

jobs:
  build_cli:
    uses: ./.github/workflows/build_images.yml
    with:
      IMAGE_ID: cli

  # Download hycom 
  plotting-surf-anom:
    runs-on: mims1
    needs: [build_cli]
    steps:
      - name: animate surface temperature anomalies
        continue-on-error: true
        run: |
          docker run \
            --memory=10g \
            --cpus=1 \
            --rm \
            -v /home/somisana/ops/anom-plot/20250812_00/sa_west_02/croco_v1.3.1/C06_I99_MERCATOR_SAWS_TPXO10:/tmp \
            ghcr.io/saeon/somisana-croco_cli_anom-plot:latest \
              crocplot \
                --fname /tmp/postprocess/croco_avg_anom.nc \
                --level -100 \
                --mp4_out /tmp/postprocess/croco_avg_temp_anom_surf.mp4 \
                --skip_time 6 \
                --var 'temp_anom' \
                --ref_date '2000-01-01 00:00:00' \
                --add_vectors False
          sudo chown somisana:somisana /home/somisana/ops/anom-plot/20250812_00/sa_west_02/croco_v1.3.1/C06_I99_MERCATOR_SAWS_TPXO10/postprocess/croco_avg_temp_anom_surf.mp4

