name: Sandbox for testing individual calleable workflows
# (not used in th operational workflow at all)

on:
  workflow_dispatch:

jobs:
  build_cli:
    uses: ./.github/workflows/build_images.yml
    with:
      IMAGE_ID: cli

  # Download hycom 
  download_hycom:
    runs-on: mims1
    needs: [build_cli]
    steps:
      - name: create the HYCOM directory
        run: |
          sudo rm -rf /home/somisana/ops/testing-hycom-download/20250506_00/downloaded_data/HYCOM
          sudo mkdir -p /home/somisana/ops/testing-hycom-download/20250506_00/downloaded_data/HYCOM
          sudo chown -R :runners /home/somisana/ops/testing-hycom-download/20250506_00/downloaded_data/HYCOM
          sudo chmod -R 774 /home/somisana/ops/testing-hycom-download/20250506_00/downloaded_data/HYCOM
      - name: Download HYCOM
        uses: nick-fields/retry@master
        with:
          timeout_minutes: 60 # Script is considered failed if this limit is reached
          retry_wait_seconds: 300 # Wait 5 minutes and try again
          max_attempts: 3
          retry_on: any
          warning_on_retry: true
          shell: bash
          continue_on_error: false
          command: |
            docker run \
              --user $(id -u):$(id -g) \
              --rm \
              -v /home/somisana/ops/testing-hycom-download/20250505_00/downloaded_data/HYCOM:/tmp \
              ghcr.io/saeon/somisana-croco_cli_testing-hycom-download:latest \
              download_hycom \
                --domain 23,24,-37,-36 \
                --depths 0,5 \
                --run_date '2025-05-06 00:00:00' \
                --hdays 5 \
                --fdays 5 \
                --savedir '/tmp/' \
                --pad True && echo "Download completed" || echo "Download failed"
