name: Sandbox for testing individual calleable workflows
# (not used in th operational workflow at all)

on:
  workflow_dispatch:

jobs:
  build_cli:
    uses: ./.github/workflows/build_images.yml
    with:
      IMAGE_ID: cli

  # Download hycom 
  plotting-surf-anom:
    runs-on: mims1
    needs: [build_cli]
    steps:
      - name: animate surface temperature anomalies
        continue-on-error: true
        run: |
          docker run \
            --memory=10g \
            --cpus=1 \
            --rm \
            -v ${{ env.RUN_DIR }}:/tmp \
            ghcr.io/saeon/somisana-croco_cli_${{ inputs.BRANCH_REF }}:latest \
              crocplot \
                --fname /tmp/postprocess/croco_avg_anom.nc \
                --level -100 \
                --mp4_out /tmp/postprocess/croco_avg_temp_anom_surf.mp4 \
                --skip_time 6 \
                --var 'temp_anom' \
                --ref_date '2000-01-01 00:00:00' \
                --add_vectors False
          sudo chown somisana:somisana ${{ env.RUN_DIR }}/postprocess/croco_avg_temp_anom_surf.mp4

