name: A way of testing individual calleable workflows
# (not used in th operational workflow at all)

on:
  workflow_dispatch:

jobs:
  # Download hycom 
  download_hycom:
    runs-on: mims1
    steps:
      - name: Download HYCOM
        uses: nick-fields/retry@master
        with:
          timeout_minutes: 60
          retry_wait_seconds: 300 
          max_attempts: 10
          retry_on: any
          warning_on_retry: true
          shell: bash
          continue_on_error: false
          command: |
            docker run \
              -e PYTHONUNBUFFERED=1 \
              --user $(id -u):$(id -g) \
              --rm \
              -v /home/somisana/ops/somisana_py/20250114_00/downloaded_data/HYCOM:/tmp \
              ghcr.io/saeon/somisana-croco_cli_somisana_py:latest \
              download_hycom \
              --domain 23,24,-37,-36 \
              --run_date '2025-01-14 00:00:00' \
              --hdays 1 \
              --fdays 1 \
              --savedir '/tmp/' && echo "Download completed" || echo "Download failed"
